### ISSUE TITLE
Using lein instructions produces error

### ISSUE THREAD

**Issue by maacl** [thegeez/databrowser#1]
Following instructions re usage with lein produces:

```
Could not find artifact net.thegeez.databrowser:databrowser-crux:jar:1.0.0-512_3 in central (https://repo1.maven.org/maven2/)
Could not find artifact net.thegeez.databrowser:databrowser-crux:jar:1.0.0-512_3 in clojars (https://repo.clojars.org/)
This could be due to a typo in :dependencies, file system permissions, or network issues.
If you are behind a proxy, try setting the 'http_proxy' environment variable.
Could not resolve dependencies

```

**Comment by thegeez** [comment]
The instructions work on my machine, the one thing I would suggest to try is to download the jar from the release page again and start from scratch.

Does the jar show up in your local maven directory (~/.m2 or something similar) after the install steps?

**Comment by maacl** [comment]
I blame the heat. Now it works. Sorry for the inconvenience.
